from decimal import Inexact
from sqlalchemy import Column, Float
from .database import Base

from sqlalchemy import Column, Integer, String, Float

class Organism(Base):
    __tablename__ = "organisms"

    org_id = Column(Integer, primary_key=True)
    division = Column(String)
    assembly = Column(String)
    taxid = Column(Integer)
    species = Column(String)
    organelle = Column(String)
    translation_table = Column(Integer)
    num_CDS = Column(Integer)
    num_codons = Column(Integer)
    GC_perc = Column(Float)
    GC1_perc = Column(Float)
    GC2_perc = Column(Float)
    GC3_perc = Column(Float)

# this is a truncated version of the above table
# to improve browser performance
class AutocompleteOrganism(Base):
    __tablename__ = "autocomplete_data"
    
    org_id = Column(Integer, primary_key=True)
    division = Column(String)
    assembly = Column(String)
    taxid = Column(Integer)
    species = Column(String)
    organelle = Column(String)
    translation_table = Column(Integer)
    num_CDS = Column(Integer)
    num_codons = Column(Integer)
    GC_perc = Column(Float)
    GC1_perc = Column(Float)
    GC2_perc = Column(Float)
    GC3_perc = Column(Float)
    category = Column(String)

class CodonUsage(Base):
    
    __tablename__ = "codon_usage"

    org_id = Column(Integer, primary_key=True)
    TTT = Column(String)
    TTC = Column(String)
    TTA = Column(String)
    TTG = Column(String)
    CTT = Column(String)
    CTC = Column(String)
    CTA = Column(String)
    CTG = Column(String)
    ATT = Column(String)
    ATC = Column(String)
    ATA = Column(String)
    ATG = Column(String)
    GTT = Column(String)
    GTC = Column(String)
    GTA = Column(String)
    GTG = Column(String)
    TAT = Column(String)
    TAC = Column(String)
    TAA = Column(String)
    TAG = Column(String)
    CAT = Column(String)
    CAC = Column(String)
    CAA = Column(String)
    CAG = Column(String)
    AAT = Column(String)
    AAC = Column(String)
    AAA = Column(String)
    AAG = Column(String)
    GAT = Column(String)
    GAC = Column(String)
    GAA = Column(String)
    GAG = Column(String)
    TCT = Column(String)
    TCC = Column(String)
    TCA = Column(String)
    TCG = Column(String)
    CCT = Column(String)
    CCC = Column(String)
    CCA = Column(String)
    CCG = Column(String)
    ACT = Column(String)
    ACC = Column(String)
    ACA = Column(String)
    ACG = Column(String)
    GCT = Column(String)
    GCC = Column(String)
    GCA = Column(String)
    GCG = Column(String)
    TGT = Column(String)
    TGC = Column(String)
    TGA = Column(String)
    TGG = Column(String)
    CGT = Column(String)
    CGC = Column(String)
    CGA = Column(String)
    CGG = Column(String)
    AGT = Column(String)
    AGC = Column(String)
    AGA = Column(String)
    AGG = Column(String)
    GGT = Column(String)
    GGC = Column(String)
    GGA = Column(String)
    GGG = Column(String)
