version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  client:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8000

networks:
  optipyzer:
    driver: bridge
