library(hash)

.codonMap = hash()

# populate
.codonMap[["ATA"]] <- "I"
.codonMap[["ATC"]] <- "I"
.codonMap[["ATT"]] <- "I"
.codonMap[["ATG"]] <- "M"
.codonMap[["ACA"]] <- "T"
.codonMap[["ACC"]] <- "T"
.codonMap[["ACG"]] <- "T"
.codonMap[["ACT"]] <- "T"
.codonMap[["AAC"]] <- "N"
.codonMap[["AAT"]] <- "N"
.codonMap[["AAA"]] <- "K"
.codonMap[["AAG"]] <- "K"
.codonMap[["AGC"]] <- "S"
.codonMap[["AGT"]] <- "S"
.codonMap[["AGA"]] <- "R"
.codonMap[["AGG"]] <- "R"
.codonMap[["CTA"]] <- "L"
.codonMap[["CTC"]] <- "L"
.codonMap[["CTG"]] <- "L"
.codonMap[["CTT"]] <- "L"
.codonMap[["CCA"]] <- "P"
.codonMap[["CCC"]] <- "P"
.codonMap[["CCG"]] <- "P"
.codonMap[["CCT"]] <- "P"
.codonMap[["CAC"]] <- "H"
.codonMap[["CAT"]] <- "H"
.codonMap[["CAA"]] <- "Q"
.codonMap[["CAG"]] <- "Q"
.codonMap[["CGA"]] <- "R"
.codonMap[["CGC"]] <- "R"
.codonMap[["CGG"]] <- "R"
.codonMap[["CGT"]] <- "R"
.codonMap[["GTA"]] <- "V"
.codonMap[["GTC"]] <- "V"
.codonMap[["GTG"]] <- "V"
.codonMap[["GTT"]] <- "V"
.codonMap[["GCA"]] <- "A"
.codonMap[["GCC"]] <- "A"
.codonMap[["GCG"]] <- "A"
.codonMap[["GCT"]] <- "A"
.codonMap[["GAC"]] <- "D"
.codonMap[["GAT"]] <- "D"
.codonMap[["GAA"]] <- "E"
.codonMap[["GAG"]] <- "E"
.codonMap[["GGA"]] <- "G"
.codonMap[["GGC"]] <- "G"
.codonMap[["GGG"]] <- "G"
.codonMap[["GGT"]] <- "G"
.codonMap[["TCA"]] <- "S"
.codonMap[["TCC"]] <- "S"
.codonMap[["TCG"]] <- "S"
.codonMap[["TCT"]] <- "S"
.codonMap[["TTC"]] <- "F"
.codonMap[["TTT"]] <- "F"
.codonMap[["TTA"]] <- "L"
.codonMap[["TTG"]] <- "L"
.codonMap[["TAC"]] <- "Y"
.codonMap[["TAT"]] <- "Y"
.codonMap[["TAA"]] <- "STOP"
.codonMap[["TAG"]] <- "STOP"
.codonMap[["TGC"]] <- "C"
.codonMap[["TGT"]] <- "C"
.codonMap[["TGA"]] <- "STOP"
.codonMap[["TGG"]] <- "W"


codon_to_aa <- function(codon) {
  return (.codonMap[[codon]])
}