name: Run Server Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2

      # setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # install dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # run tests
      - name: Run Tests
        run: |
          pytest ./tests --verbose
